"""app/routes.py — All API route definitions"""
from fastapi import APIRouter, UploadFile, File, HTTPException, BackgroundTasks, Request
from pydantic import BaseModel
from typing import Optional, List
import uuid

from orchestrator.orchestrator import Orchestrator
from audit.audit_logger import AuditLogger
from memory.short_term_memory import ShortTermMemory
from utils.logger import get_logger

logger = get_logger(__name__)
router       = APIRouter()
orchestrator = Orchestrator()
audit        = AuditLogger()


# ── Request / Response Models ─────────────────────────────────────────────────

class WorkflowTriggerRequest(BaseModel):
    workflow_type: str
    payload:       dict
    priority:      Optional[str] = "normal"


class TaskApprovalRequest(BaseModel):
    workflow_id:  str
    step_name:    str
    approved:     bool
    human_input:  Optional[dict] = None
    approver_id:  str


class TaskUpdateRequest(BaseModel):
    """Employee or manager marks a task done / in-progress / needs help"""
    workflow_id: str
    task_id:     str
    status:      str             # done | in_progress | needs_help | pending
    note:        Optional[str] = ""
    updated_by:  Optional[str] = "employee"


class WorkflowStatusResponse(BaseModel):
    workflow_id:           str
    status:                str
    current_step:          str
    completed_steps:       List[str]
    retry_count:           int
    sla_remaining_minutes: Optional[float]


# ── Health ────────────────────────────────────────────────────────────────────

@router.get("/health")
async def health_check():
    """System health check"""
    return {"status": "ok", "service": "agentic-ai-system"}


# ── Workflow Triggers ─────────────────────────────────────────────────────────

@router.post("/workflow/trigger")
async def trigger_workflow(request: WorkflowTriggerRequest, background_tasks: BackgroundTasks):
    """Trigger any enterprise workflow by type"""
    workflow_id = str(uuid.uuid4())
    logger.info(f"Triggering workflow: {request.workflow_type} | id={workflow_id}")
    background_tasks.add_task(
        orchestrator.run_workflow,
        workflow_id=workflow_id,
        workflow_type=request.workflow_type,
        payload=request.payload,
        priority=request.priority,
    )
    return {
        "workflow_id": workflow_id,
        "status":      "started",
        "message":     f"Workflow {request.workflow_type} initiated",
    }


@router.post("/meeting/upload")
async def upload_meeting_transcript(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(...),
):
    """Upload a meeting transcript (.txt) to trigger meeting intelligence"""
    workflow_id = str(uuid.uuid4())
    content     = await file.read()
    text        = content.decode("utf-8", errors="ignore")
    logger.info(f"Meeting transcript uploaded | workflow_id={workflow_id} | size={len(text)} chars")
    background_tasks.add_task(
        orchestrator.run_workflow,
        workflow_id=workflow_id,
        workflow_type="meeting",
        payload={"transcript": text, "filename": file.filename},
        priority="normal",
    )
    return {
        "workflow_id": workflow_id,
        "status":      "processing",
        "message":     "Meeting transcript received",
    }


# ── Status & Tasks ────────────────────────────────────────────────────────────

@router.get("/workflow/{workflow_id}/status")
async def get_workflow_status(workflow_id: str):
    """Get real-time status of a running workflow"""
    state = ShortTermMemory.get_state(workflow_id)
    if not state:
        raise HTTPException(status_code=404, detail="Workflow not found")
    return WorkflowStatusResponse(
        workflow_id=workflow_id,
        status=state.get("status", "unknown"),
        current_step=state.get("current_step", ""),
        completed_steps=state.get("completed_steps", []),
        retry_count=state.get("retry_count", 0),
        sla_remaining_minutes=state.get("sla_remaining_minutes"),
    )


@router.get("/workflow/{workflow_id}/tasks")
async def get_workflow_tasks(workflow_id: str):
    """Get all tasks generated by a meeting or workflow run"""
    # Check workflow state first
    state = ShortTermMemory.get_state(workflow_id)

    # Also check tracker store
    tracker_key   = f"tracker:{workflow_id}:tasks"
    tracker_tasks = ShortTermMemory.get(tracker_key) or []

    if not state and not tracker_tasks:
        raise HTTPException(status_code=404, detail="Workflow not found")

    # Merge and deduplicate tasks from both sources
    seen      = set()
    all_tasks = []

    for task in (state or {}).get("tasks", []):
        tid = task.get("id", "")
        if tid not in seen:
            seen.add(tid)
            all_tasks.append(task)

    for task in tracker_tasks:
        tid = task.get("id", "")
        if tid not in seen:
            seen.add(tid)
            all_tasks.append(task)

    return {"workflow_id": workflow_id, "tasks": all_tasks, "count": len(all_tasks)}


# ── Task Status Update (Employee marks done) ──────────────────────────────────

@router.post("/task/update")
async def update_task_status(request: TaskUpdateRequest):
    """
    Employee or manager updates task status.

    This is the endpoint called when:
      - Employee clicks 'Mark Done' in Streamlit dashboard
      - Manager approves via Swagger UI
      - Slack webhook receives button click

    Valid statuses: done | in_progress | needs_help | pending
    """
    valid_statuses = {"done", "in_progress", "needs_help", "pending", "cancelled"}
    if request.status not in valid_statuses:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid status '{request.status}'. Must be one of: {valid_statuses}",
        )

    # Update in tracker store
    tracker_key = f"tracker:{request.workflow_id}:tasks"
    tasks       = ShortTermMemory.get(tracker_key) or []
    updated     = False

    for task in tasks:
        if task.get("id") == request.task_id:
            from datetime import datetime, timezone
            task["status"]     = request.status
            task["updated_at"] = datetime.now(timezone.utc).isoformat()
            task["updated_by"] = request.updated_by
            if request.note:
                task["status_note"] = request.note
            updated = True
            logger.info(
                f"Task updated | task={request.task_id} | "
                f"status={request.status} | by={request.updated_by}"
            )
            break

    if tasks:
        ShortTermMemory.set(tracker_key, tasks)

    # Also update in workflow state tasks
    state = ShortTermMemory.get_state(request.workflow_id)
    if state:
        for task in state.get("tasks", []):
            if task.get("id") == request.task_id:
                from datetime import datetime, timezone
                task["status"]     = request.status
                task["updated_at"] = datetime.now(timezone.utc).isoformat()
                task["updated_by"] = request.updated_by
                if request.note:
                    task["status_note"] = request.note
                updated = True
                break

    # Log to audit trail
    audit.log(
        agent_id="employee_update",
        action="TASK_STATUS_UPDATED",
        workflow_id=request.workflow_id,
        step_name="task_update",
        input_summary=f"task={request.task_id} | by={request.updated_by}",
        output_summary=f"status={request.status} | note={request.note}",
        confidence=1.0,
    )

    return {
        "status":  "ok",
        "updated": updated,
        "task_id": request.task_id,
        "new_status": request.status,
        "message": f"Task marked as '{request.status}' by {request.updated_by}",
    }


# ── Slack Webhook (receives button clicks from Slack) ────────────────────────

@router.post("/slack/webhook")
async def slack_webhook(request: Request):
    """
    Receives interactive button click events from Slack.
    When employee clicks 'Mark Done' button in Slack DM,
    Slack sends a POST to this endpoint.

    Button value format: 'action|task_id|workflow_id'
    e.g. 'done|task_abc123|workflow-uuid-here'
    """
    try:
        body    = await request.form()
        payload = body.get("payload", "{}")

        import json
        data = json.loads(payload)

        # Extract action from button click
        actions = data.get("actions", [])
        if not actions:
            return {"ok": True}

        action      = actions[0]
        action_id   = action.get("action_id", "")
        value       = action.get("value", "")
        user        = data.get("user", {}).get("name", "unknown")

        # Parse value: "done|task_id|workflow_id"
        parts = value.split("|")
        if len(parts) != 3:
            logger.warning(f"Invalid Slack button value: {value}")
            return {"ok": True}

        action_type, task_id, workflow_id = parts

        # Map Slack action to task status
        status_map = {
            "done":      "done",
            "progress":  "in_progress",
            "help":      "needs_help",
            "reassign":  "pending",
        }
        new_status = status_map.get(action_type, "in_progress")

        logger.info(
            f"Slack button clicked | user={user} | "
            f"action={action_type} | task={task_id}"
        )

        # Update task status using same logic as /task/update
        tracker_key = f"tracker:{workflow_id}:tasks"
        tasks       = ShortTermMemory.get(tracker_key) or []

        for task in tasks:
            if task.get("id") == task_id:
                from datetime import datetime, timezone
                task["status"]     = new_status
                task["updated_at"] = datetime.now(timezone.utc).isoformat()
                task["updated_by"] = user
                break

        if tasks:
            ShortTermMemory.set(tracker_key, tasks)

        audit.log(
            agent_id="slack_webhook",
            action="TASK_STATUS_UPDATED",
            workflow_id=workflow_id,
            step_name="slack_button",
            input_summary=f"task={task_id} | user={user}",
            output_summary=f"status={new_status}",
            confidence=1.0,
        )

        return {"ok": True, "message": f"Task {task_id} marked as {new_status}"}

    except Exception as e:
        logger.error(f"Slack webhook error: {e}")
        return {"ok": True}


# ── Human Approval Gate ───────────────────────────────────────────────────────

@router.post("/workflow/approve")
async def approve_workflow_step(request: TaskApprovalRequest):
    """Human approves or rejects a step that hit the human gate"""
    logger.info(
        f"Human approval | workflow={request.workflow_id} | "
        f"approved={request.approved}"
    )
    ShortTermMemory.set_human_approval(
        workflow_id=request.workflow_id,
        step_name=request.step_name,
        approved=request.approved,
        human_input=request.human_input or {},
        approver_id=request.approver_id,
    )
    audit.log(
        agent_id="human_gate",
        action="HUMAN_APPROVAL_RECEIVED",
        workflow_id=request.workflow_id,
        step_name=request.step_name,
        output_summary=f"approved={request.approved} by {request.approver_id}",
        confidence=1.0,
    )
    return {"status": "ok", "message": "Approval recorded"}


# ── Audit Trail ───────────────────────────────────────────────────────────────

@router.get("/audit/{workflow_id}")
async def get_audit_trail(workflow_id: str):
    """Retrieve full audit trail for a workflow"""
    entries = audit.get_trail(workflow_id)
    return {"workflow_id": workflow_id, "entries": entries, "count": len(entries)}


@router.get("/audit/all/recent")
async def get_recent_audit(limit: int = 50):
    """Get most recent audit log entries across all workflows"""
    return {"entries": audit.get_recent(limit=limit)}